Unexpected keyword argument 'bf16' : Modified train.py to handle exceptions appropriately
openai/weak-to-strong pull request #20
Opened 2023-12-21 06:32 UTC by srivhash

Added a custom function that checks if the enlisted parameters within kwargs are valid.
If the type error is thrown, then the function ignores that specific parameter and checks for the other parameters.

2023-12-22 03:38 UTC, WuTheFWasThat requested changes

2023-12-22 03:38 UTC, WuTheFWasThat commented on weak_to_strong/train.py
> +def try_initialize_model_with_kwargs_2(model_config, custom_kwargs, num_labels=2, linear_probe=False):
the only difference is device_map="auto"?  you could just pass dict(**custom_kwargs, device_map="auto") and use a single function

2023-12-22 03:38 UTC, WuTheFWasThat commented on weak_to_strong/train.py
> +            return try_initialize_model_with_kwargs(model_config, new_kwargs, num_labels, linear_probe)
this is a bug i think?  recursing into the wrong function

2023-12-22 07:21 UTC, srivhash commented
Added the requested changes

2024-01-23 06:27 UTC, WuTheFWasThat commented
using https://github.com/openai/weak-to-strong/pull/22 instead

2024-01-23 06:27 UTC, closed without merging